#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
# (c) Copyright 2016 - 2022 Xilinx, Inc. All rights reserved.
set -e

export TS_TOPDIR="$(cd "$(dirname "$(which "$0")")/.."; pwd -P)"
. ${TS_TOPDIR}/scripts/guess.sh

doxygen_debug=false

do_default=true
do_pdf=false
do_html=false

help() {
    cat <<EOF
Tool is used to generate documentation for the dpdk-ethdev-ts test suite.

It's based on doxygen and doxyrest.

Usage: ./$0 [--help] [--debug] [--html] [--pdf]

Options:
    --html: generate html documentation (default)
    --pdf: generate pdf documentation
    --debug: enable debug mode
    --help: show this help message
EOF
}

for opt ; do
    case "${opt}" in
        --help|-h)
            help
            exit 0
            ;;
        -d|--debug)
            doxygen_debug=true
            ;;
        --html)
            do_default=false
            do_html=true
            ;;
        --pdf)
            do_default=false
            do_pdf=true
            ;;
        *)
            echo "Unknown option: $opt" >&2
            help
            exit 1
            ;;
    esac
done

if [ -z "$DOXYREST_PREFIX" ]; then
    $TE_BASE/scripts/doxyrest_deploy.sh --how
    exit -1
fi
[ -z "$DOXYREST_BIN" ] && DOXYREST_BIN="$DOXYREST_PREFIX/bin/doxyrest"

[ -z "$SPHINX_BUILD_BIN" ] && SPHINX_BUILD_BIN="sphinx-build"
if ! which $SPHINX_BUILD_BIN >/dev/null; then
    echo "Please install sphinx before:"
    echo " $ pip install sphinx sphinx_rtd_theme"
    exit -2
fi

pushd ${TS_TOPDIR} >/dev/null

if $doxygen_debug ; then
   doxygen -d extcmd -d filteroutput ts/Doxyfile
else
  doxygen ts/Doxyfile >/dev/null
fi

DOXYREST_OPTS=(
    --config=ts/doc/doxyrest-config.lua
    --frame-dir=$DOXYREST_PREFIX/share/doxyrest/frame/cfamily
    --frame-dir=$DOXYREST_PREFIX/share/doxyrest/frame/common
)

${DOXYREST_BIN} "${DOXYREST_OPTS[@]}" || exit 1

if $do_default; then
    do_html=true
    do_pdf=false
fi

if $do_html; then
    SPHINX_BUILD_OPTS=(
        -j auto                     # use cpu count
        -q                          # be quite: warn and error only
        ts/doc                      # input
        ts/doc/generated/html       # output
    )

    ${SPHINX_BUILD_BIN} "${SPHINX_BUILD_OPTS[@]}"
fi

if $do_pdf; then
    make -C ${TS_TOPDIR}/ts/doc latexpdf

    # Note, the name depends on conf.py!
    echo Open: $(realpath ts/doc/generated/latex/dpdk_ethdev_test_suite.pdf)
fi

popd >/dev/null
